# Site settings
title: A portfolio of Damodar Dikonda
description: A portfolio of Damodar Dikonda
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Damodar Dikonda
user_description: Undergrad student at Zeal College of Engineering and Research, Pune. I expect to graduate in Summer, 2021.
user_title: Aspiring Software Developer
email: damodar5dikonda@gmail.com
twitter_username: lorem_ipsum
github_username:  damodar454
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
